import{S as p}from"./assets/vendor-BQtLt1QN.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const t of r)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function a(r){const t={};return r.integrity&&(t.integrity=r.integrity),r.referrerPolicy&&(t.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?t.credentials="include":r.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(r){if(r.ep)return;r.ep=!0;const t=a(r);fetch(r.href,t)}})();async function d(e,o=1,a=12){const t=`https://pixabay.com/api/?key=47684004-d700c1255eaadac249fdd5630&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${a}`;try{const i=await fetch(t);if(!i.ok)throw new Error("Failed to fetch images");return await i.json()}catch(i){throw console.error("Error fetching images:",i),i}}function u(e){const o=document.querySelector(".gallery"),a=e.map(n=>`
      <a href="${n.largeImageURL}" class="gallery-item">
        <div class="photo-card">
          <img src="${n.webformatURL}" alt="${n.tags}" loading="lazy" />
          <div class="info">
            <p><b>Likes:</b> ${n.likes}</p>
            <p><b>Views:</b> ${n.views}</p>
            <p><b>Comments:</b> ${n.comments}</p>
            <p><b>Downloads:</b> ${n.downloads}</p>
          </div>
        </div>
      </a>
    `).join("");o.innerHTML=a}function g(){const e=document.querySelector(".gallery");e.innerHTML=""}function f(){document.querySelector(".loader").classList.remove("hidden")}function h(){document.querySelector(".loader").classList.add("hidden")}function m(e){iziToast.error({title:"Error",message:e})}function l(e){iziToast.info({title:"Info",message:e})}const w=document.querySelector("#search-form"),L=document.querySelector('input[name="searchQuery"]');let c=1,s="",y=new p(".gallery a");w.addEventListener("submit",async e=>{if(e.preventDefault(),s=L.value.trim(),!s){l("Please enter a search term.");return}g(),c=1,f();try{const o=await d(s,c);if(o.hits.length===0){l("Sorry, there are no images matching your search query. Please try again!");return}u(o.hits),y.refresh()}catch{m("An error occurred while fetching images.")}finally{h()}});window.addEventListener("scroll",async()=>{if(window.innerHeight+window.scrollY>=document.body.offsetHeight-100){c+=1,f();try{const e=await d(s,c);if(e.hits.length===0){l("No more images to load.");return}u(e.hits),y.refresh()}catch{m("An error occurred while fetching additional images.")}finally{h()}}});
//# sourceMappingURL=index.js.map
